var data = {  
    "message":"accurate",
    "cod":"200",
    "count":15,
    "list":[  
        {  
            "id":4172131,
            "name":"Sarasota",
            "coord":{  
                "lon":-82.530647,
                "lat":27.33643
            },
            "main":{  
                "temp":304.97,
                "humidity":60,
                "pressure":1020,
                "temp_min":303.15,
                "temp_max":308.25
            },
            "dt":1466454718,
            "wind":{  
                "speed":3.86,
                "deg":65.0022
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":76
            },
            "weather":[  
                {  
                    "id":803,
                    "main":"Clouds",
                    "description":"broken clouds",
                    "icon":"04d"
                }
            ]
        },
        {  
            "id":4166298,
            "name":"North Sarasota",
            "coord":{  
                "lon":-82.518433,
                "lat":27.37393
            },
            "main":{  
                "temp":303.54,
                "humidity":0,
                "pressure":0,
                "temp_min":300.37,
                "temp_max":307.95
            },
            "dt":1466454900,
            "wind":{  
                "speed":3.86,
                "deg":65.0022
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":76
            },
            "weather":[  
                {  
                    "id":803,
                    "main":"Clouds",
                    "description":"broken clouds",
                    "icon":"04d"
                }
            ]
        },
        {  
            "id":4160752,
            "name":"Kensington Park",
            "coord":{  
                "lon":-82.49649,
                "lat":27.359489
            },
            "main":{  
                "temp":304.92,
                "humidity":60,
                "pressure":1020,
                "temp_min":303.15,
                "temp_max":307.95
            },
            "dt":1466454900,
            "wind":{  
                "speed":4.66,
                "deg":83.0022
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":92
            },
            "weather":[  
                {  
                    "id":804,
                    "main":"Clouds",
                    "description":"overcast clouds",
                    "icon":"04d"
                }
            ]
        },
        {  
            "id":4173634,
            "name":"Southgate",
            "coord":{  
                "lon":-82.509819,
                "lat":27.3081
            },
            "main":{  
                "temp":304.92,
                "humidity":60,
                "pressure":1020,
                "temp_min":303.15,
                "temp_max":307.95
            },
            "dt":1466454900,
            "wind":{  
                "speed":3.86,
                "deg":65.0022
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":76
            },
            "weather":[  
                {  
                    "id":803,
                    "main":"Clouds",
                    "description":"broken clouds",
                    "icon":"04d"
                }
            ]
        },
        {  
            "id":4172935,
            "name":"Siesta Key",
            "coord":{  
                "lon":-82.551491,
                "lat":27.301991
            },
            "main":{  
                "temp":304.31,
                "humidity":0,
                "pressure":0,
                "temp_min":301.76,
                "temp_max":307.95
            },
            "dt":1466454900,
            "wind":{  
                "speed":3.86,
                "deg":65.0022
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":76
            },
            "weather":[  
                {  
                    "id":803,
                    "main":"Clouds",
                    "description":"broken clouds",
                    "icon":"04d"
                }
            ]
        },
        {  
            "id":4153186,
            "name":"Desoto Lakes",
            "coord":{  
                "lon":-82.489822,
                "lat":27.371429
            },
            "main":{  
                "temp":304.92,
                "humidity":60,
                "pressure":1020,
                "temp_min":303.15,
                "temp_max":307.95
            },
            "dt":1466454900,
            "wind":{  
                "speed":4.66,
                "deg":83.0022
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":92
            },
            "weather":[  
                {  
                    "id":804,
                    "main":"Clouds",
                    "description":"overcast clouds",
                    "icon":"04d"
                }
            ]
        },
        {  
            "id":4173558,
            "name":"South Sarasota",
            "coord":{  
                "lon":-82.532883,
                "lat":27.28616
            },
            "main":{  
                "temp":304.92,
                "humidity":60,
                "pressure":1020,
                "temp_min":303.15,
                "temp_max":307.95
            },
            "dt":1466454900,
            "wind":{  
                "speed":4.31,
                "deg":71.0022
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":44
            },
            "weather":[  
                {  
                    "id":802,
                    "main":"Clouds",
                    "description":"scattered clouds",
                    "icon":"03d"
                }
            ]
        },
        {  
            "id":4172150,
            "name":"Sarasota Springs",
            "coord":{  
                "lon":-82.479538,
                "lat":27.308941
            },
            "main":{  
                "temp":304.31,
                "humidity":0,
                "pressure":0,
                "temp_min":301.76,
                "temp_max":307.95
            },
            "dt":1466454900,
            "wind":{  
                "speed":4.66,
                "deg":83.0022
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":92
            },
            "weather":[  
                {  
                    "id":804,
                    "main":"Clouds",
                    "description":"overcast clouds",
                    "icon":"04d"
                }
            ]
        },
        {  
            "id":4170018,
            "name":"Ridge Wood Heights",
            "coord":{  
                "lon":-82.513153,
                "lat":27.28727
            },
            "main":{  
                "temp":304.32,
                "humidity":0,
                "pressure":0,
                "temp_min":301.76,
                "temp_max":307.95
            },
            "dt":1466454900,
            "wind":{  
                "speed":4.31,
                "deg":71.0022
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":44
            },
            "weather":[  
                {  
                    "id":802,
                    "main":"Clouds",
                    "description":"scattered clouds",
                    "icon":"03d"
                }
            ]
        },
        {  
            "id":4175136,
            "name":"The Meadows",
            "coord":{  
                "lon":-82.468979,
                "lat":27.36171
            },
            "main":{  
                "temp":303.54,
                "humidity":0,
                "pressure":0,
                "temp_min":300.37,
                "temp_max":307.95
            },
            "dt":1466454900,
            "wind":{  
                "speed":4.66,
                "deg":83.0022
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":92
            },
            "weather":[  
                {  
                    "id":804,
                    "main":"Clouds",
                    "description":"overcast clouds",
                    "icon":"04d"
                }
            ]
        },
        {  
            "id":4173460,
            "name":"South Gate Ridge",
            "coord":{  
                "lon":-82.496758,
                "lat":27.28644
            },
            "main":{  
                "temp":304.92,
                "humidity":60,
                "pressure":1020,
                "temp_min":303.15,
                "temp_max":307.95
            },
            "dt":1466454900,
            "wind":{  
                "speed":5.36,
                "deg":86.5022
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":92
            },
            "weather":[  
                {  
                    "id":804,
                    "main":"Clouds",
                    "description":"overcast clouds",
                    "icon":"04d"
                }
            ]
        },
        {  
            "id":4156340,
            "name":"Fruitville",
            "coord":{  
                "lon":-82.457603,
                "lat":27.329769
            },
            "main":{  
                "temp":304.12,
                "humidity":0,
                "pressure":0,
                "temp_min":301.76,
                "temp_max":307.95
            },
            "dt":1466454900,
            "wind":{  
                "speed":4.66,
                "deg":83.0022
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":92
            },
            "weather":[  
                {  
                    "id":804,
                    "main":"Clouds",
                    "description":"overcast clouds",
                    "icon":"04d"
                }
            ]
        },
        {  
            "id":4146587,
            "name":"Ballentine Manor",
            "coord":{  
                "lon":-82.565376,
                "lat":27.40143
            },
            "main":{  
                "temp":304.91,
                "humidity":60,
                "pressure":1020,
                "temp_min":303.15,
                "temp_max":307.95
            },
            "dt":1466454900,
            "wind":{  
                "speed":3.86,
                "deg":65.0022
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":76
            },
            "weather":[  
                {  
                    "id":803,
                    "main":"Clouds",
                    "description":"broken clouds",
                    "icon":"04d"
                }
            ]
        },
        {  
            "id":4147145,
            "name":"Bee Ridge",
            "coord":{  
                "lon":-82.480652,
                "lat":27.283939
            },
            "main":{  
                "temp":304.32,
                "humidity":0,
                "pressure":0,
                "temp_min":301.76,
                "temp_max":307.95
            },
            "dt":1466454900,
            "wind":{  
                "speed":5.36,
                "deg":86.5022
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":92
            },
            "weather":[  
                {  
                    "id":804,
                    "main":"Clouds",
                    "description":"overcast clouds",
                    "icon":"04d"
                }
            ]
        },
        {  
            "id":4178215,
            "name":"Whitfield",
            "coord":{  
                "lon":-82.565933,
                "lat":27.411711
            },
            "main":{  
                "temp":303.53,
                "humidity":0,
                "pressure":0,
                "temp_min":300.37,
                "temp_max":307.95
            },
            "dt":1466454900,
            "wind":{  
                "speed":3.86,
                "deg":65.0022
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":76
            },
            "weather":[  
                {  
                    "id":803,
                    "main":"Clouds",
                    "description":"broken clouds",
                    "icon":"04d"
                }
            ]
        }
    ]
};

module.exports = data;